### ISSUE TITLE
oauth_user_auth() takes exactly 1 argument (2 given)

### ISSUE THREAD

**Issue by hhessel** [clemesha/django-piston-oauth-example#1]
TypeError at /oauth/authorize/

oauth_user_auth() takes exactly 1 argument (2 given)

Request Method:     POST
Request URL:    http://www.xxxx.com/api/oauth/authorize/
Django Version:     1.2.1
Exception Type:     TypeError
Exception Value:    

oauth_user_auth() takes exactly 1 argument (2 given)

Exception Location:     /usr/lib/python2.5/site-packages/django/contrib/auth/decorators.py in _wrapped_view, line 25
Python Executable:  /usr/bin/python
Python Version:     2.5.2

**Comment by benjamindell** [comment]
I am having this exact same issue. Does anyone know what is causing it? I am essentially going here (http://localhost:8000/api/oauth/authorize/?oauth_token=TOKEN) and submitting the form. Once submitted i get the same error above. Any ideas?

**Comment by bkroeze** [comment]
I figured it out!  The OAUTH_CALLBACK_VIEW in the settings file points to the same view that returns the callback view.  In other words, it is an infinite loop.  It is throwing an error because the view is called with two parameters (request, token), but the view only takes one.

Solution, write a simple callback view like this one (I put it in api/views.py)

```
from django.shortcuts import render_to_response
from django.template import RequestContext

def request_token_ready(request, token):
    error = request.GET.get('error', '')
    ctx = RequestContext(request, {
        'error' : error,
        'token' : token})
    return render_to_response('api/request_token_ready.html',
                          context_instance = ctx)
```

Then, update your settings.py file like so:

OAUTH_CALLBACK_VIEW = "api.views.request_token_ready"

**Comment by bkroeze** [comment]
Argh, markdown somehow didn't write in the "OAUTH_CALLBACK_VIEW" on the previous comment.

**Comment by hhessel** [comment]
Can you provided a forked version of this repo that fixes this problem?!

**Comment by nat-e** [comment]
@bkroeze: You are not supposed to do this. Piston already provides two different views depending on the HTTP method of the request (GET/POST). You can see this in `piston/authentication.py`:

```
def oauth_user_oauth(request):
    # Some code
    if request.metoauthhod == "GET":
        params = oauth_request.get_normalized_parameters()
        oauth_view = getattr(settings, 'OAUTH_AUTH_VIEW', None)
        if oauth_view is None:
            return oauth_auth_view(request, token, callback, params)
        else:
            return get_callable(oauth_view)(request, token, callback, params)
    elif request.method == "POST":
        try:
            form = forms.OAuthAuthenticationForm(request.POST)
            if form.is_valid():
                token = oauth_server.authorize_token(token, request.user)
                args = '?'+token.to_string(only_key=True)
            else:
                if callback:
                    args = '?error=%s' % 'Access not granted by user.'
                else:
                    return get_callable(callback)(request, token, form) 

            if not callback:
                callback = getattr(settings, 'OAUTH_CALLBACK_VIEW')
                return get_callable(callback)(request, token)

            response = HttpResponseRedirect(callback+args)

        except oauth.OAuthError, err:
            response = send_oauth_error(err)
```

Basically the first time the consumer sends a GET HTTP request, it displays the form, and when the form is submitted, it sends a POST HTTP request that redirects the User to the callback URL (which should point to the consumer's website) which should have been provided by the consumer.

The problem described in this issue is due to the fact that the consumer does not setup any callback URL. The callback URL should be passed by using the `oauth_callback` parameter.
I do agree that the error mechanism is not really clear and I would have preferred piston to crash before displaying the authorization form if no callback is given.

nbarraille
